### ISSUE TITLE
Connpass からイベント内容を取得してきて、そのイベント内容を下に反映したい (was: 説明の書き換えが細かく発生するので結局手間)

### ISSUE THREAD

**Issue by iso2022jp** [binnmti/ConnpassAutomator#11]
## TODO

- [x] Selenium で Connpass のイベント編集画面から説明文を取得できるか調査する
- [x] イベントを作成しないメソッドがあるのにEventCreatorだったのでリネーム
- [x] Connpass からイベント内容を取得してきて、そのイベント内容を下に反映する
- [x] 最終確認が出来てない。（別原因で落ちた？）

## 問題

* 意外に説明文を書き換えることが多い
* Connpass の Web サイト側で書き換えてしまう
    * ツール側の説明に（当然）同期されない 
    * Web の説明をローカルに落とす手段がない

## 現状

* `Connpass からイベント内容を取得してきて、そのイベント内容を下に反映する。` ボタンはある（未実装）
* （少なくとも）使いはじめの際にに Connpass からイベント内容をコピーで持ってこないといけない

## 方法

* 通常のイベントページは HTML 化されてしまっている
   * HTML から Markdown を生成する力業もあるが、元々 Markdown にあったコメント類は復元できない
   * 改変になるので使い勝手は悪い
* イベント管理から編集モードに入り、 `Description` の本文のどこかをクリックすると編集モードになる
    * Selenium でこの画面には到達できたとして、この内容を取得する方法があるかどうか

**Comment by zbdk** [comment]
■Selenium で Connpass のイベント編集画面から説明文を取得できるか調査する
issue-11ブランチで説明文のMarkdownを取得するテストを追加しました

**Comment by binnmti** [comment]
FindEventContainsEventTitleとは別のUrlを取れるメソッドを作る。（やり方は幾つかある）
FindEventContainsEventTitleの引数が大きすぎるので変更する
GetMarkdownToConnpassWebSiteの中でそのURLを使った実装に変える
ボタンを変更して正しく実装する

**Comment by binnmti** [comment]
実装完了
