### ISSUE TITLE
ConnpassAutomatorのメイン画面のレイアウトの見直し

### ISSUE THREAD

**Issue by kazuhito-m** [binnmti/ConnpassAutomator#5]
## 主旨(なぜこれをするのか)

- 左端のもともとパスワード入力してたトコを、ダイアログとして分離することになった
-  ついては「左側の領域」自体を無くしてしまいたい
  - 残ったパーツは少ない
  - もともと「デッドスペース」が多かった
- 残ってるパーツ
    1. パスワード変更ダイアログ表示ボタン
    0. イベント作成(Selenium実行)ボタン
    0. 「作成と共に公開される」チェックボックス
    0. イベント作成後リンク/ボタン(一度イベント作成すると、表示・有効化される)

### ユーザー設定ボタン

- そもそも「アクティブに変更するものではない」ので、通常作業の(目の)動線上に要らない
- 結局「右上」か「左下」くらいしかない
    - 右上だとコンボの長さを削ったり、ボタンが一つだけ異質だったり
    - なので「左下」が妥当かもね？

### 「イベント作成」ボタン

- 作業の動線的に「入力してから押すもの」「プリセットを選択してから確認して押すもの」である
    - 上にあるのは、ちょと違う
- 「一般的な入力フォーム」の設計法に従えば自明
    - Windowsの「コミットボタン群」の観点でも、下、さらに言えば右下が望ましい

### 「作成と共に公開される」チェックボックス

- 「「イベント作成」ボタン」の従属物だと考えるの
    - 「イベント作成」ボタンの左側に置いとくのが、まあ自然

### イベント作成後リンク/ボタン(一度イベント作成すると、表示・有効化される)

- 三浦案(実装コスト度外視)
    - 下のボタン領域に「前回の結果を表示」チェックボックスを置く
    - 上記をOnにした場合、トップモースト＆子フォームで「イベント作成後リンク・URLコピーボタン」が盛り込まれたフォームを表示
    - 絶えず浮いてるので、いつでも消せるし、チェックをOnにしたらいつでも(前回結果だけど)出せる
- 松井案
    - チェックボックスを表示する
    - チェックをされると、Windowが伸びる
- 「決定！」牛戸案
    - 下のボタン域は普通にあって、その下に「結果表示域」がある
    - 普段は何もない灰色領域だが、一度実行すると出てくる
        - その領域に「Connpass自体のURL」とか「静的だろうが動的だろうが、情報域として存在する」というものとして予約しとく
        - アプリの情報(Version情報)とかを出すのも、意味から考えると意図通り
    - 最終的に「ステータスバー」と同じ役目になる

![実装イメージ(荒削り)](https://user-images.githubusercontent.com/2945461/193420568-f11e860e-2b6a-48bf-94d5-5d81316819d9.png)

## 後で詰めること

チェック済みは、タスクカード化済み。

- [x] リサイズの動き(特に横の大きさ変更)
- [x] 領域のサイズ感
- [x] ~~イベント作成後リンク等の「表示されてない時」の表示~~
- [x] 「ユーザー設定ダイアログ」を「初回勝手に出すか」の仕様
- [x] ~~「右長画面」にして下のボタン域と情報域を左右に並べ、「イベント説明」を最大化する…かどうか~~
  - 今のまま __で__ いい(松井談)
  - 「イベント説明」の入力欄が「使いやすく(デカく)できるか」が争点だが、「リサイズを工夫する」ことによって、ユーザー体験的には「自らで使いやすくできる」ので、対して問題としない(ので現状維持)
- [x] タブインデックス

**Comment by iso2022jp** [comment]
![image](https://user-images.githubusercontent.com/1140380/193420534-f858aaa7-6630-451a-9c1d-debfafa62a0c.png)

**Comment by kazuhito-m** [comment]
全てをタスクに出した(別の問題とした)ので、Close。
